heat_template_version: 2014-10-16

#
# you can deploy this template using the following command:
# 'openstack stack create -t singleMachineDevEnv.yaml --parameter key_name=<publicKeyName> --parameter ip_whitelist=<ipAddrRangInCIDR>'
#
# after successful stack creation you can login with 
# ssh -l ubuntu <externalIP> 
# 


description: Simple template to deploy a single compute instance
  with external network and associated security group.

parameters:
 key_name:
  type: string
 public_network_id:
  type: string
  default: caf8de33-1059-4473-a2c1-2a62d12294fa
 ip_whitelist:
  type: string
  description: ip address or range in CIDR


resources:
  allow_static_ip:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming traffic only from specified IP.
      name: allow incoming traffic, tcp
      rules: [{direction: ingress, remote_ip_prefix: {get_param: ip_whitelist}, port_range_min: 1, port_range_max: 65535, protocol: tcp} ]

  secured_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: Ubuntu 14.04 sys11-cloudimg amd64
      flavor: m1.micro
      user_data_format: RAW
      networks:
        - port: { get_resource: example_port }

  example_port:
    type: OS::Neutron::Port
    properties:
      security_groups: [ get_resource: allow_static_ip ]
      network_id: { get_resource: example_net}

  example_net:
    type: OS::Neutron::Net
    properties: 
      name: example-net

  example_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: example_subnet
      dns_nameservers:
        - 37.123.105.116
        - 37.123.105.117
      network_id: {get_resource: example_net}
      ip_version: 4
      cidr: 10.0.0.0/8
      allocation_pools:
      - {start: 10.0.0.10, end: 10.0.0.250}

  example_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {"network": { get_param: public_network_id }}

  router_subnet_connect:
    type: OS::Neutron::RouterInterface
    depends_on: [ example_subnet, example_router ]
    properties:
      router_id: { get_resource: example_router }
      subnet: { get_resource: example_subnet }

  example_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network_id }
      port_id: { get_resource: example_port }
