heat_template_version: 2016-04-08
#
# you can deploy this template using the following command:
# 'openstack stack create -t example.yaml -e example-env.yaml <stackName>'
# 
# after successful stack creation you can login with 
# ssh -l syseleven <externalIP> 
# 

description: Stack that launches a single server

parameters:
  public_network:
    type: string
  net:
    type: string
  image:
    type: string
  flavor:
    type: string
  ssh_keys:
    type: comma_delimited_list

resources:

  host:
    type: OS::Nova::Server
    depends_on: [ cloud-init-config, port ]
    properties:
      name: 
        list_join: [ '-', [ { get_param: "OS::stack_name" }, 'example-server' ]]
      user_data_format: RAW
      user_data: { get_resource: cloud-init-config }    
      image: { get_param: image } 
      flavor: { get_param: flavor } 
      networks:
        - port: { get_resource: port }

  cloud-init-config:
   # cloud init resource
   type: OS::Heat::CloudConfig
   properties:
    cloud_config:
      manage_etc_hosts: true
      users:
        - name: syseleven
          gecos: syseleven Stack user
          sudo: ALL=(ALL) NOPASSWD:ALL
          shell: /bin/bash
          lock-passwd: false
          ssh-authorized-keys: { get_param: ssh_keys }  

  allow_ssh:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming SSH and ICMP traffic from anywhere.
      name: 
        list_join: [ '-', [ { get_param: "OS::stack_name" }, 'kickstart', 'allow incoming traffic, tcp port 22 and icmp']]
      rules: 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 22, port_range_max: 22, protocol: tcp } 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: icmp } 

  port:
    type: OS::Neutron::Port
    depends_on: [ allow_ssh ]
    properties:
      network: { get_param: net }
      security_groups: [ get_resource: allow_ssh ]

  floating_ip:
    type: OS::Neutron::FloatingIP
    depends_on: [ port ]
    properties:
      floating_network: { get_param: public_network }
      port_id: { get_resource: port }
      
