heat_template_version: 2015-04-30

description: Simple template to deploy NFS clients

parameters:
  name:
    type: string
  syseleven_net:
    type: string

resources:
  nfs_server:
    type: OS::Nova::Server 
    properties:
      image: Ubuntu 16.04 sys11-cloudimg amd64 
      user_data_format: RAW
      user_data: { get_resource: cloud-init-config }
      name:  { get_param: name }
      flavor: m1.micro
      networks:
        - port: { get_resource: syseleven_port }
  
  allow_ssh:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming traffic on ssh port and icmp
      name: allow incoming traffic on ssh and icmp
      rules: [{direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 22, port_range_max: 22, protocol: tcp} , {direction: ingress, protocol: icmp}]

  syseleven_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: syseleven_net}
      security_groups: [ {get_resource: allow_ssh}, default ]
  
  cloud-init-config:
   # cloud init demo resource
   type: OS::Heat::CloudConfig
   properties:
     cloud_config:
       runcmd:
         - /root/client_nfs_share.sh
       write_files:
         -  content: { get_file: scripts/client_nfs_share.sh }
            permissions: 0755
            path: /root/client_nfs_share.sh
       users:
           - name: syseleven
             gecos:  Workshop user
             lock-passwd: false
             sudo: ALL=(ALL) NOPASSWD:ALL
             shell: /bin/bash
             ssh-authorized-keys:
               - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBHhKPUBIv4EhNIDrXYsoBPNTCzMXtIkCcqEiXjx1AH8WNRHYN7blzV+qv9SJOzfi9OcfQ3o+qR2YwYT+z2464crW9xZHrtEerVDWMeCs3ZsnGxiFM40xpKhWHuTZNv+Y+07t8CHAdfGlSM3st2NrdwB2qWBTvoXTuhc9/4UeEM5rsLFDFIb84P4VXiMLooo8ovDWZ4I1A1+cmbiG9PDPIXn2I3LLvXfSn7rbTal5dJixZAfue1sKCwoFxzEIjdD2MRfkkwcYRbm2wyU2Gf3XTE4OOl/AIoCvgnp2+zFH6rdVme+lsX32ddS2dayoU50VpMz1jWq+fR5bnGyvYnJux janpeschke@ws171.sys11.net'

outputs:
  interesting_stuff:
    description: show syseleven_port infos
    value: { get_attr: [syseleven_port, show] }
