heat_template_version: 2016-04-08

parameters:
  name:
    type: string
  syseleven_net:
    type: string
  image:
    type: string
  flavor:
    type: string
  consul_mastertoken:
    type: string
  consul_agenttoken:
    type: string
  ssh_keys:
    type: comma_delimited_list
#  volume: 
#    type: string

resources:

  dbserver:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      user_data_format: RAW
      user_data: { get_resource: cloud-init-config }    
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: dbserver_port }

#  # attach volume to a server
#  db_volume_attach:
#    depends_on: dbserver
#    type: OS::Cinder::VolumeAttachment
#    properties:
#      instance_uuid: { get_resource: dbserver }
#      volume_id: { get_param: volume }

  cloud-init-config:
   # cloud init demo resource
   type: OS::Heat::CloudConfig
   properties:
     cloud_config:
       runcmd:
         - [ /root/install_generic.sh, { get_param: consul_mastertoken }, { get_param: consul_agenttoken } ]
         - /root/install_dbserver.sh
       write_files:
         -  content: { get_file: scripts/install_generic.sh }
            permissions: 0700
            path: /root/install_generic.sh
         -  content: { get_file: scripts/install_dbserver.sh }
            permissions: 0700
            path: /root/install_dbserver.sh
       users:
         -  name: syseleven
            gecos: service user
            lock-passwd: false
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            ssh-authorized-keys: { get_param: ssh_keys }
       apt:
         sources:
           percona_repo:
             source: "deb http://repo.percona.com/apt xenial main"
             keyid: 8507EFA5 
             filename: xtradb.list


## deb http://repo.percona.com/apt xenial main
## deb-src http://repo.percona.com/apt xenial main

  dbserver_port:
    type: OS::Neutron::Port
    properties:
      name: dbserver port
      network: { get_param: syseleven_net}
