heat_template_version: 2016-04-08
description: substack3
resources:
  fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "ext-net"

outputs:
  fip1:
    description: Floating IP address
    value: { get_attr: [ fip, floating_ip_address ] }
