heat_template_version: 2014-10-16

description: >
    Creates a router + net + subnet + interface + VM
parameters:
  key_name:
    type: string
  public_network_id:
    type: string
    default: caf8de33-1059-4473-a2c1-2a62d12294fa 
  image:
    type: string
    default: Ubuntu 16.04 sys11-cloudimg amd64 
  flavor:
    type: string
    default: m1.small

resources:
  example_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      user_data_format: RAW
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: example_port }

  example_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: network}
      security_groups: [{ get_resource: server_security_group }]

  example_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network_id }
      port_id: { get_resource: example_port }

  network:
    type: OS::Neutron::Net
    properties:
      name: example-test-net

  subnet:
    type: OS::Neutron::Subnet
    depends_on: router
    properties:
      name: examplae_subnet
      dns_nameservers:
        - 8.8.4.4
      network: {get_resource: network}
      ip_version: 4
      cidr: 10.0.0.0/24
      allocation_pools:
      - {start: 10.0.0.10, end: 10.0.0.250}

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {"network": { get_param: public_network_id }}
      name: example_natpoint

  router_subnet_bridge:
    type: OS::Neutron::RouterInterface
    depends_on:  subnet
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet }

  server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Open SSH and Ping traffic.
      name: single-server-security-group 
      rules: [
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: tcp,
        port_range_min: 22,
        port_range_max: 22},
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: icmp}]
