heat_template_version: 2014-10-16

description: Associate a FIP to a server port with Neutron.

parameters:
  floatingip_id:
    type: string
    default: 367e3d6d-9409-40c3-8b74-844aed5d25d6
  port_id:
    type: string


resources:
  loadbalancer_floating_ip_1_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_param: floatingip_id }
      port_id: { get_param: port_id }
      