heat_template_version: 2014-10-16
#
# you can deploy this template using the following command:
# 'openstack stack create -t sysElevenStackKickstart.yaml --parameter key_name=<publicKeyName> <stackName>'
# 
# or you can just paste it into the web-ui under "orchestration" >> "launch stack"
#
# after successful stack creation you can login with 
# ssh -l syseleven <externalIP> 
# 

description: Simple template to deploy a single compute instance
  with external network (login will be possible through vnc console and via SSH).
  It deploys a user named syseleven with sudo permissions and the openstack-CLI-tools.
  This template is prepared to be used with https://dashboard.cloud.syseleven.net

parameters:
 ssh_keys:
  type: comma_delimited_list
 key_name:
  type: string
 public_network_id:
  type: string
  default: caf8de33-1059-4473-a2c1-2a62d12294fa 

resources:
  allow_ssh:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming SSH and ICMP traffic from anywhere.
      name: allow incoming traffic, tcp port 22 and icmp
      rules: 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 22, port_range_max: 22, protocol: tcp } 
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: icmp } 

  host:
    type: OS::Nova::Server
    properties:
      name: kickstart
      user_data_format: RAW
      user_data: { get_resource: cloud-init-config }    
      image: Ubuntu Server 16.04 LTS 
      key_name: {get_param: key_name}
      flavor: m1.micro
      networks:
        - port: { get_resource: port }

  cloud-init-config:
   # cloud init resource
   type: OS::Heat::CloudConfig
   properties:
     cloud_config:
       manage_etc_hosts: true
       users:
           - name: syseleven
             gecos: SysEleven Stack user
             sudo: ALL=(ALL) NOPASSWD:ALL
             shell: /bin/bash
       write_files:
         -  content: |
              #!/usr/bin/env bash
              # wait for valid network
              until ping -c 1 syseleven.de > /dev/null; do sleep 2; done
              # wait for a valid user
              until id syseleven > /dev/null; do sleep 2; done
              mkdir /home/syseleven/.ssh
              curl -s http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key > /home/syseleven/.ssh/authorized_keys
              cat <<EOF> /home/syseleven/.ssh/config
              Host 185.56.* 
               UserKnownHostsFile=/dev/null
               StrictHostKeyChecking=no
              EOF
              chown -R syseleven: /home/syseleven
              # disable ubuntu landscape scripts
              curl "https://raw.githubusercontent.com/syseleven/heattemplates-examples/master/gettingStarted/motd.txt" > /etc/motd 
              chmod 400 /etc/update-motd.d/*
            path: /root/inject_userkey
            permissions: 0700
         # don't replace content in this hot template, only write your credentials inside the newly generated vm!
         -  content: | 
              # replace "demo_user", "demo_project_id" and "demo_password" by your corresponding credentials

              export OS_USERNAME="demo_user"
              export OS_PROJECT_ID="demo_project_id"
              export OS_PASSWORD="demo_password"

              # the following lines don't need to be changed
              export OS_AUTH_URL=https://api.cbk.cloud.syseleven.net:5000/v3
              export OS_IDENTITY_API_VERSION=3
              export OS_USER_DOMAIN_NAME="Default"
              export OS_INTERFACE=public
              export OS_ENDPOINT_TYPE=public
              export OS_REGION_NAME="cbk"

              # Don't leave a blank variable, unset it if it was empty
              if [ -z "$OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi
              if [ -z "$OS_USER_DOMAIN_NAME" ]; then unset OS_USER_DOMAIN_NAME; fi
              unset OS_TENANT_ID
              unset OS_TENANT_NAME
            path: /etc/skel/openrc
            owner: root
            permissions: 0600
         - content: |
              #!/usr/bin/env bash
              until id syseleven > /dev/null; do sleep 2; done
              url="https://releases.hashicorp.com/terraform/0.10.2/terraform_0.10.2_linux_amd64.zip"
              bin="/home/syseleven/bin"
              tmp="/tmp/terraform.zip"
              /bin/mkdir -p $bin
              /usr/bin/curl -s -o $tmp $url
              /usr/bin/unzip -q $tmp -d $bin
              /bin/chown syseleven:syseleven $bin/terraform
              /bin/chown -R syseleven:syseleven $bin/
              if [ -f $tmp ]; then rm $tmp; fi
              if [ -x $bin/terraform ]; then exit 0; else (echo "Error while installing terraform"; exit 99); fi
           path: /root/terra-install.sh
           owner: root
           permissions: 0700

       runcmd:
         - /root/inject_userkey
         - /root/terra-install.sh
       packages:
         - git
         - wget
         - unzip
         - screen
         - python-cinderclient
         - python-glanceclient
         - python-novaclient
         - python-keystoneclient
         - python-neutronclient
         - python-heatclient
         - python-openstackclient
             
  port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: net}
      security_groups: [ get_resource: allow_ssh ]

  net:
    type: OS::Neutron::Net
    properties: 
      name: kickstart-net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name: kickstart-subnet
      dns_nameservers:
        - 37.123.105.116
        - 37.123.105.117
      network: {get_resource: net}
      ip_version: 4
      cidr: 10.0.0.0/24
      allocation_pools:
      - {start: 10.0.0.10, end: 10.0.0.250}

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {"network": { get_param: public_network_id }}
      name: kickstart-router

  router_subnet_bridge:
    type: OS::Neutron::RouterInterface
    depends_on: subnet
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network_id }
      port_id: { get_resource: port }
